# Generated by Django 2.2.1 on 2019-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_links_movies_ratings_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.FloatField(),
        ),
    ]
