# Generated by Django 2.2.1 on 2019-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=20000)),
            ],
        ),
    ]
