# Generated by Django 2.2.1 on 2019-05-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('imie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nazwisko', models.CharField(max_length=30)),
            ],
        ),
    ]
